### PR TITLE
Entry fixes

### PR DESCRIPTION
**Pull request by LordTermor**
This fixes some desc-file parsing logic so manually uploaded packages will get proper descriptions in database.

### CODE REVIEW

**Comment by romangg** [comment]
Is there an issue ticket for these fixes?

**Comment by LordTermor** [comment]
No. 

It was an issue I've found and decided to fix right after that as it's pretty major

**Comment by romangg** [comment]
* line length of commit messages must be 90 chars or less
*  can you describe the first commit better? I don't get the commit message and why it didn't work before.

**Comment by LordTermor** [comment]
> line length of commit messages must be 90 chars or less

from error it sounds like a body line limit

> body's lines must not be longer than 90 characters

That sounds like a very weird limitation. What would be the point? Should body be multilined manually then?

> can you describe the first commit better? I don't get the commit message and why it didn't work before.

Package entities used to contain only file path and version but with https://github.com/anydistro/bxt/pull/68/commits/8976f71e4c760834b10513b1e1e8db3b306efd77 I've added full `desc` contents to it because it's anyway stored like that and loading desc from archive on persistence step is costy. But I forgot to update some functions so they resulted incomplete package entity on manual upload. This PR fixes it.

**Comment by romangg** [comment]
> That sounds like a very weird limitation. What would be the point?

Traditionally there are [good](https://github.com/torvalds/linux/pull/17#issuecomment-5661185) [reasons](https://cbea.ms/git-commit/?ref=blog.bajonczak.com#wrap-72) to have some limit. I use 90 instead of 72 because displays are larger nowadays and max code line lengths in projects have typically also increased from 80 to something between 100 and 120.

> Should body be multilined manually then?

Yes, there is [a setting](https://stackoverflow.com/a/11023282) though for vim for example to do it automatically.

> Package entities used to contain only file path and version but with https://github.com/anydistro/bxt/commit/8976f71e4c760834b10513b1e1e8db3b306efd77 I've added full desc contents to it because it's anyway stored like that and loading desc from archive on persistence step is costy. But I forgot to update some functions so they resulted incomplete package entity on manual upload. This PR fixes it.

Thanks, that makes it clearer. For things like this having regression tests would be nice.

**Review by romangg — APPROVED** [review]

**Pull request merged**
